/*试卷增加删除字段*/
ALTER TABLE "TestPaper"  ADD COLUMN IF NOT EXISTS "Tp_IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX  IF NOT EXISTS "TestPaper_IX_IsDeleted" ON "TestPaper"("Tp_IsDeleted");
ALTER TABLE "TestPaper" ADD COLUMN IF NOT EXISTS "Tp_DeleteTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX  IF NOT EXISTS "TestPaper_IX_DeleteTime" ON "TestPaper"("Tp_DeleteTime");

/*课程，专业，增加是否删除的时间*/
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "Cou_DeleteTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX  IF NOT EXISTS "Course_IX_DeleteTime" ON "Course"("Cou_DeleteTime");
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "Sbj_DeleteTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX  IF NOT EXISTS "Subject_IX_DeleteTime" ON "Subject"("Sbj_DeleteTime");

/*试题，增加是否删除的时间*/
ALTER TABLE "Questions" ADD COLUMN IF NOT EXISTS "Qus_DeleteTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX  IF NOT EXISTS "Questions_IX_DeleteTime" ON "Questions"("Qus_DeleteTime");


/*试题分类、知识点、考试试卷、关键字，增加是否删除的时间*/
ALTER TABLE "QuesPart" ADD COLUMN IF NOT EXISTS "Qp_DeleteTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX  IF NOT EXISTS "QuesPart_IX_DeleteTime" ON "QuesPart"("Qp_DeleteTime");
ALTER TABLE "QuesKnowledge" ADD COLUMN IF NOT EXISTS "Qk_DeleteTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX  IF NOT EXISTS "QuesKnowledge_IX_DeleteTime" ON "QuesKnowledge"("Qk_DeleteTime");
ALTER TABLE "ExamTestPaper" ADD COLUMN IF NOT EXISTS "Etp_DeleteTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX  IF NOT EXISTS "ExamTestPaper_IX_DeleteTime" ON "ExamTestPaper"("Etp_DeleteTime");
ALTER TABLE "QuesTags" ADD COLUMN IF NOT EXISTS "Qtag_DeleteTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX  IF NOT EXISTS "QuesTags_IX_DeleteTime" ON "QuesTags"("Qtag_DeleteTime");